export const people = [
  {
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [
      'STRING_TO_REPLACE/api/vehicles/14/',
      'STRING_TO_REPLACE/api/vehicles/30/',
    ],
    starships: [
      'STRING_TO_REPLACE/api/starships/12/',
      'STRING_TO_REPLACE/api/starships/22/',
    ],
    created: '2014-12-09T13:50:51.644000Z',
    edited: '2014-12-20T21:17:56.891000Z',
    url: 'STRING_TO_REPLACE/api/people/1/',
    imageURL: 'STRING_TO_REPLACE/images/people/Luke Skywalker.png',
  },
  {
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hair_color: 'n/a',
    skin_color: 'gold',
    eye_color: 'yellow',
    birth_year: '112BBY',
    gender: 'n/a',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/2/'],
    vehicles: [],
    starships: [],
    created: '2014-12-10T15:10:51.357000Z',
    edited: '2014-12-20T21:17:50.309000Z',
    url: 'STRING_TO_REPLACE/api/people/2/',
    imageURL: 'STRING_TO_REPLACE/images/people/C-3PO.png',
  },
  {
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, blue',
    eye_color: 'red',
    birth_year: '33BBY',
    gender: 'n/a',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/2/'],
    vehicles: [],
    starships: [],
    created: '2014-12-10T15:11:50.376000Z',
    edited: '2014-12-20T21:17:50.311000Z',
    url: 'STRING_TO_REPLACE/api/people/3/',
    imageURL: 'STRING_TO_REPLACE/images/people/R2-D2.png',
  },
  {
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    birth_year: '41.9BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/13/'],
    created: '2014-12-10T15:18:20.704000Z',
    edited: '2014-12-20T21:17:50.313000Z',
    url: 'STRING_TO_REPLACE/api/people/4/',
    imageURL: 'STRING_TO_REPLACE/images/people/Darth Vader.png',
  },
  {
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '19BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/2/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/30/'],
    starships: [],
    created: '2014-12-10T15:20:09.791000Z',
    edited: '2014-12-20T21:17:50.315000Z',
    url: 'STRING_TO_REPLACE/api/people/5/',
    imageURL: 'STRING_TO_REPLACE/images/people/Leia Organa.png',
  },
  {
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hair_color: 'brown, grey',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '52BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-10T15:52:14.024000Z',
    edited: '2014-12-20T21:17:50.317000Z',
    url: 'STRING_TO_REPLACE/api/people/6/',
    imageURL: 'STRING_TO_REPLACE/images/people/Owen Lars.png',
  },
  {
    name: 'Beru Whitesun lars',
    height: '165',
    mass: '75',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '47BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-10T15:53:41.121000Z',
    edited: '2014-12-20T21:17:50.319000Z',
    url: 'STRING_TO_REPLACE/api/people/7/',
    imageURL: 'STRING_TO_REPLACE/images/people/Beru Whitesun lars.png',
  },
  {
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, red',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'n/a',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: ['STRING_TO_REPLACE/api/films/1/'],
    species: ['STRING_TO_REPLACE/api/species/2/'],
    vehicles: [],
    starships: [],
    created: '2014-12-10T15:57:50.959000Z',
    edited: '2014-12-20T21:17:50.321000Z',
    url: 'STRING_TO_REPLACE/api/people/8/',
    imageURL: 'STRING_TO_REPLACE/images/people/R5-D4.png',
  },
  {
    name: 'Biggs Darklighter',
    height: '183',
    mass: '84',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '24BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: ['STRING_TO_REPLACE/api/films/1/'],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/12/'],
    created: '2014-12-10T15:59:50.509000Z',
    edited: '2014-12-20T21:17:50.323000Z',
    url: 'STRING_TO_REPLACE/api/people/9/',
    imageURL: 'STRING_TO_REPLACE/images/people/Biggs Darklighter.png',
  },
  {
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hair_color: 'auburn, white',
    skin_color: 'fair',
    eye_color: 'blue-gray',
    birth_year: '57BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/20/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/38/'],
    starships: [
      'STRING_TO_REPLACE/api/starships/48/',
      'STRING_TO_REPLACE/api/starships/59/',
      'STRING_TO_REPLACE/api/starships/64/',
      'STRING_TO_REPLACE/api/starships/65/',
      'STRING_TO_REPLACE/api/starships/74/',
    ],
    created: '2014-12-10T16:16:29.192000Z',
    edited: '2014-12-20T21:17:50.325000Z',
    url: 'STRING_TO_REPLACE/api/people/10/',
    imageURL: 'STRING_TO_REPLACE/images/people/Obi-Wan Kenobi.png',
  },
  {
    name: 'Anakin Skywalker',
    height: '188',
    mass: '84',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '41.9BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [
      'STRING_TO_REPLACE/api/vehicles/44/',
      'STRING_TO_REPLACE/api/vehicles/46/',
    ],
    starships: [
      'STRING_TO_REPLACE/api/starships/39/',
      'STRING_TO_REPLACE/api/starships/59/',
      'STRING_TO_REPLACE/api/starships/65/',
    ],
    created: '2014-12-10T16:20:44.310000Z',
    edited: '2014-12-20T21:17:50.327000Z',
    url: 'STRING_TO_REPLACE/api/people/11/',
    imageURL: 'STRING_TO_REPLACE/images/people/Anakin Skywalker.png',
  },
  {
    name: 'Wilhuff Tarkin',
    height: '180',
    mass: 'unknown',
    hair_color: 'auburn, grey',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '64BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/21/',
    films: ['STRING_TO_REPLACE/api/films/1/', 'STRING_TO_REPLACE/api/films/6/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-10T16:26:56.138000Z',
    edited: '2014-12-20T21:17:50.330000Z',
    url: 'STRING_TO_REPLACE/api/people/12/',
    imageURL: 'STRING_TO_REPLACE/images/people/Wilhuff Tarkin.png',
  },
  {
    name: 'Chewbacca',
    height: '228',
    mass: '112',
    hair_color: 'brown',
    skin_color: 'unknown',
    eye_color: 'blue',
    birth_year: '200BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/14/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/3/'],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/19/'],
    starships: [
      'STRING_TO_REPLACE/api/starships/10/',
      'STRING_TO_REPLACE/api/starships/22/',
    ],
    created: '2014-12-10T16:42:45.066000Z',
    edited: '2014-12-20T21:17:50.332000Z',
    url: 'STRING_TO_REPLACE/api/people/13/',
    imageURL: 'STRING_TO_REPLACE/images/people/Chewbacca.png',
  },
  {
    name: 'Han Solo',
    height: '180',
    mass: '80',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '29BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/22/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
    ],
    species: [],
    vehicles: [],
    starships: [
      'STRING_TO_REPLACE/api/starships/10/',
      'STRING_TO_REPLACE/api/starships/22/',
    ],
    created: '2014-12-10T16:49:14.582000Z',
    edited: '2014-12-20T21:17:50.334000Z',
    url: 'STRING_TO_REPLACE/api/people/14/',
    imageURL: 'STRING_TO_REPLACE/images/people/Han Solo.png',
  },
  {
    name: 'Greedo',
    height: '173',
    mass: '74',
    hair_color: 'n/a',
    skin_color: 'green',
    eye_color: 'black',
    birth_year: '44BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/23/',
    films: ['STRING_TO_REPLACE/api/films/1/'],
    species: ['STRING_TO_REPLACE/api/species/4/'],
    vehicles: [],
    starships: [],
    created: '2014-12-10T17:03:30.334000Z',
    edited: '2014-12-20T21:17:50.336000Z',
    url: 'STRING_TO_REPLACE/api/people/15/',
    imageURL: 'STRING_TO_REPLACE/images/people/Greedo.png',
  },
  {
    name: 'Jabba Desilijic Tiure',
    height: '175',
    mass: '1,358',
    hair_color: 'n/a',
    skin_color: 'green-tan, brown',
    eye_color: 'orange',
    birth_year: '600BBY',
    gender: 'hermaphrodite',
    homeworld: 'STRING_TO_REPLACE/api/planets/24/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/4/',
    ],
    species: ['STRING_TO_REPLACE/api/species/5/'],
    vehicles: [],
    starships: [],
    created: '2014-12-10T17:11:31.638000Z',
    edited: '2014-12-20T21:17:50.338000Z',
    url: 'STRING_TO_REPLACE/api/people/16/',
    imageURL: 'STRING_TO_REPLACE/images/people/Jabba Desilijic Tiure.png',
  },
  {
    name: 'Wedge Antilles',
    height: '170',
    mass: '77',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'hazel',
    birth_year: '21BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/22/',
    films: [
      'STRING_TO_REPLACE/api/films/1/',
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
    ],
    species: [],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/14/'],
    starships: ['STRING_TO_REPLACE/api/starships/12/'],
    created: '2014-12-12T11:08:06.469000Z',
    edited: '2014-12-20T21:17:50.341000Z',
    url: 'STRING_TO_REPLACE/api/people/18/',
    imageURL: 'STRING_TO_REPLACE/images/people/Wedge Antilles.png',
  },
  {
    name: 'Jek Tono Porkins',
    height: '180',
    mass: '110',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/26/',
    films: ['STRING_TO_REPLACE/api/films/1/'],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/12/'],
    created: '2014-12-12T11:16:56.569000Z',
    edited: '2014-12-20T21:17:50.343000Z',
    url: 'STRING_TO_REPLACE/api/people/19/',
    imageURL: 'STRING_TO_REPLACE/images/people/Jek Tono Porkins.png',
  },
  {
    name: 'Yoda',
    height: '66',
    mass: '17',
    hair_color: 'white',
    skin_color: 'green',
    eye_color: 'brown',
    birth_year: '896BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/28/',
    films: [
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/6/'],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:26:01.042000Z',
    edited: '2014-12-20T21:17:50.345000Z',
    url: 'STRING_TO_REPLACE/api/people/20/',
    imageURL: 'STRING_TO_REPLACE/images/people/Yoda.png',
  },
  {
    name: 'Palpatine',
    height: '170',
    mass: '75',
    hair_color: 'grey',
    skin_color: 'pale',
    eye_color: 'yellow',
    birth_year: '82BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: [
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:48:05.971000Z',
    edited: '2014-12-20T21:17:50.347000Z',
    url: 'STRING_TO_REPLACE/api/people/21/',
    imageURL: 'STRING_TO_REPLACE/images/people/Palpatine.png',
  },
  {
    name: 'Boba Fett',
    height: '183',
    mass: '78.2',
    hair_color: 'black',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '31.5BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/10/',
    films: [
      'STRING_TO_REPLACE/api/films/2/',
      'STRING_TO_REPLACE/api/films/3/',
      'STRING_TO_REPLACE/api/films/5/',
    ],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/21/'],
    created: '2014-12-15T12:49:32.457000Z',
    edited: '2014-12-20T21:17:50.349000Z',
    url: 'STRING_TO_REPLACE/api/people/22/',
    imageURL: 'STRING_TO_REPLACE/images/people/Boba Fett.png',
  },
  {
    name: 'IG-88',
    height: '200',
    mass: '140',
    hair_color: 'none',
    skin_color: 'metal',
    eye_color: 'red',
    birth_year: '15BBY',
    gender: 'none',
    homeworld: 'STRING_TO_REPLACE/api/planets/28/',
    films: ['STRING_TO_REPLACE/api/films/2/'],
    species: ['STRING_TO_REPLACE/api/species/2/'],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:51:10.076000Z',
    edited: '2014-12-20T21:17:50.351000Z',
    url: 'STRING_TO_REPLACE/api/people/23/',
    imageURL: 'STRING_TO_REPLACE/images/people/IG-88.png',
  },
  {
    name: 'Bossk',
    height: '190',
    mass: '113',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'red',
    birth_year: '53BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/29/',
    films: ['STRING_TO_REPLACE/api/films/2/'],
    species: ['STRING_TO_REPLACE/api/species/7/'],
    vehicles: [],
    starships: [],
    created: '2014-12-15T12:53:49.297000Z',
    edited: '2014-12-20T21:17:50.355000Z',
    url: 'STRING_TO_REPLACE/api/people/24/',
    imageURL: 'STRING_TO_REPLACE/images/people/Bossk.png',
  },
  {
    name: 'Lando Calrissian',
    height: '177',
    mass: '79',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '31BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/30/',
    films: ['STRING_TO_REPLACE/api/films/2/', 'STRING_TO_REPLACE/api/films/3/'],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/10/'],
    created: '2014-12-15T12:56:32.683000Z',
    edited: '2014-12-20T21:17:50.357000Z',
    url: 'STRING_TO_REPLACE/api/people/25/',
    imageURL: 'STRING_TO_REPLACE/images/people/Lando Calrissian.png',
  },
  {
    name: 'Lobot',
    height: '175',
    mass: '79',
    hair_color: 'none',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '37BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/6/',
    films: ['STRING_TO_REPLACE/api/films/2/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-15T13:01:57.178000Z',
    edited: '2014-12-20T21:17:50.359000Z',
    url: 'STRING_TO_REPLACE/api/people/26/',
    imageURL: 'STRING_TO_REPLACE/images/people/Lobot.png',
  },
  {
    name: 'Ackbar',
    height: '180',
    mass: '83',
    hair_color: 'none',
    skin_color: 'brown mottle',
    eye_color: 'orange',
    birth_year: '41BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/31/',
    films: ['STRING_TO_REPLACE/api/films/3/'],
    species: ['STRING_TO_REPLACE/api/species/8/'],
    vehicles: [],
    starships: [],
    created: '2014-12-18T11:07:50.584000Z',
    edited: '2014-12-20T21:17:50.362000Z',
    url: 'STRING_TO_REPLACE/api/people/27/',
    imageURL: 'STRING_TO_REPLACE/images/people/Ackbar.png',
  },
  {
    name: 'Mon Mothma',
    height: '150',
    mass: 'unknown',
    hair_color: 'auburn',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '48BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/32/',
    films: ['STRING_TO_REPLACE/api/films/3/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-18T11:12:38.895000Z',
    edited: '2014-12-20T21:17:50.364000Z',
    url: 'STRING_TO_REPLACE/api/people/28/',
    imageURL: 'STRING_TO_REPLACE/images/people/Mon Mothma.png',
  },
  {
    name: 'Arvel Crynyd',
    height: 'unknown',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/28/',
    films: ['STRING_TO_REPLACE/api/films/3/'],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/28/'],
    created: '2014-12-18T11:16:33.020000Z',
    edited: '2014-12-20T21:17:50.367000Z',
    url: 'STRING_TO_REPLACE/api/people/29/',
    imageURL: 'STRING_TO_REPLACE/images/people/Arvel Crynyd.png',
  },
  {
    name: 'Wicket Systri Warrick',
    height: '88',
    mass: '20',
    hair_color: 'brown',
    skin_color: 'brown',
    eye_color: 'brown',
    birth_year: '8BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/7/',
    films: ['STRING_TO_REPLACE/api/films/3/'],
    species: ['STRING_TO_REPLACE/api/species/9/'],
    vehicles: [],
    starships: [],
    created: '2014-12-18T11:21:58.954000Z',
    edited: '2014-12-20T21:17:50.369000Z',
    url: 'STRING_TO_REPLACE/api/people/30/',
    imageURL: 'STRING_TO_REPLACE/images/people/Wicket Systri Warrick.png',
  },
  {
    name: 'Nien Nunb',
    height: '160',
    mass: '68',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/33/',
    films: ['STRING_TO_REPLACE/api/films/3/'],
    species: ['STRING_TO_REPLACE/api/species/10/'],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/10/'],
    created: '2014-12-18T11:26:18.541000Z',
    edited: '2014-12-20T21:17:50.371000Z',
    url: 'STRING_TO_REPLACE/api/people/31/',
    imageURL: 'STRING_TO_REPLACE/images/people/Nien Nunb.png',
  },
  {
    name: 'Qui-Gon Jinn',
    height: '193',
    mass: '89',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '92BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/28/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: [],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/38/'],
    starships: [],
    created: '2014-12-19T16:54:53.618000Z',
    edited: '2014-12-20T21:17:50.375000Z',
    url: 'STRING_TO_REPLACE/api/people/32/',
    imageURL: 'STRING_TO_REPLACE/images/people/Qui-Gon Jinn.png',
  },
  {
    name: 'Nute Gunray',
    height: '191',
    mass: '90',
    hair_color: 'none',
    skin_color: 'mottled green',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/18/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/11/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:05:57.357000Z',
    edited: '2014-12-20T21:17:50.377000Z',
    url: 'STRING_TO_REPLACE/api/people/33/',
    imageURL: 'STRING_TO_REPLACE/images/people/Nute Gunray.png',
  },
  {
    name: 'Finis Valorum',
    height: '170',
    mass: 'unknown',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '91BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/9/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:21:45.915000Z',
    edited: '2014-12-20T21:17:50.379000Z',
    url: 'STRING_TO_REPLACE/api/people/34/',
    imageURL: 'STRING_TO_REPLACE/images/people/Finis Valorum.png',
  },
  {
    name: 'Padmé Amidala',
    height: '185',
    mass: '45',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '46BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [],
    starships: [
      'STRING_TO_REPLACE/api/starships/39/',
      'STRING_TO_REPLACE/api/starships/49/',
      'STRING_TO_REPLACE/api/starships/64/',
    ],
    created: '2014-12-19T17:28:26.926000Z',
    edited: '2014-12-20T21:17:50.381000Z',
    url: 'STRING_TO_REPLACE/api/people/35/',
    imageURL: 'STRING_TO_REPLACE/images/people/Padmé Amidala.png',
  },
  {
    name: 'Jar Jar Binks',
    height: '196',
    mass: '66',
    hair_color: 'none',
    skin_color: 'orange',
    eye_color: 'orange',
    birth_year: '52BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/4/', 'STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/12/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:29:32.489000Z',
    edited: '2014-12-20T21:17:50.383000Z',
    url: 'STRING_TO_REPLACE/api/people/36/',
    imageURL: 'STRING_TO_REPLACE/images/people/Jar Jar Binks.png',
  },
  {
    name: 'Roos Tarpals',
    height: '224',
    mass: '82',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/12/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:32:56.741000Z',
    edited: '2014-12-20T21:17:50.385000Z',
    url: 'STRING_TO_REPLACE/api/people/37/',
    imageURL: 'STRING_TO_REPLACE/images/people/Roos Tarpals.png',
  },
  {
    name: 'Rugor Nass',
    height: '206',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/12/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:33:38.909000Z',
    edited: '2014-12-20T21:17:50.388000Z',
    url: 'STRING_TO_REPLACE/api/people/38/',
    imageURL: 'STRING_TO_REPLACE/images/people/Rugor Nass.png',
  },
  {
    name: 'Ric Olié',
    height: '183',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/40/'],
    created: '2014-12-19T17:45:01.522000Z',
    edited: '2014-12-20T21:17:50.392000Z',
    url: 'STRING_TO_REPLACE/api/people/39/',
    imageURL: 'STRING_TO_REPLACE/images/people/Ric Olié.png',
  },
  {
    name: 'Watto',
    height: '137',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'blue, grey',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/34/',
    films: ['STRING_TO_REPLACE/api/films/4/', 'STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/13/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:48:54.647000Z',
    edited: '2014-12-20T21:17:50.395000Z',
    url: 'STRING_TO_REPLACE/api/people/40/',
    imageURL: 'STRING_TO_REPLACE/images/people/Watto.png',
  },
  {
    name: 'Sebulba',
    height: '112',
    mass: '40',
    hair_color: 'none',
    skin_color: 'grey, red',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/35/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/14/'],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:53:02.586000Z',
    edited: '2014-12-20T21:17:50.397000Z',
    url: 'STRING_TO_REPLACE/api/people/41/',
    imageURL: 'STRING_TO_REPLACE/images/people/Sebulba.png',
  },
  {
    name: 'Quarsh Panaka',
    height: '183',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '62BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:55:43.348000Z',
    edited: '2014-12-20T21:17:50.399000Z',
    url: 'STRING_TO_REPLACE/api/people/42/',
    imageURL: 'STRING_TO_REPLACE/images/people/Quarsh Panaka.png',
  },
  {
    name: 'Shmi Skywalker',
    height: '163',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '72BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: ['STRING_TO_REPLACE/api/films/4/', 'STRING_TO_REPLACE/api/films/5/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-19T17:57:41.191000Z',
    edited: '2014-12-20T21:17:50.401000Z',
    url: 'STRING_TO_REPLACE/api/people/43/',
    imageURL: 'STRING_TO_REPLACE/images/people/Shmi Skywalker.png',
  },
  {
    name: 'Darth Maul',
    height: '175',
    mass: '80',
    hair_color: 'none',
    skin_color: 'red',
    eye_color: 'yellow',
    birth_year: '54BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/36/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/22/'],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/42/'],
    starships: ['STRING_TO_REPLACE/api/starships/41/'],
    created: '2014-12-19T18:00:41.929000Z',
    edited: '2014-12-20T21:17:50.403000Z',
    url: 'STRING_TO_REPLACE/api/people/44/',
    imageURL: 'STRING_TO_REPLACE/images/people/Darth Maul.png',
  },
  {
    name: 'Bib Fortuna',
    height: '180',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'pink',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/37/',
    films: ['STRING_TO_REPLACE/api/films/3/'],
    species: ['STRING_TO_REPLACE/api/species/15/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T09:47:02.512000Z',
    edited: '2014-12-20T21:17:50.407000Z',
    url: 'STRING_TO_REPLACE/api/people/45/',
    imageURL: 'STRING_TO_REPLACE/images/people/Bib Fortuna.png',
  },
  {
    name: 'Ayla Secura',
    height: '178',
    mass: '55',
    hair_color: 'none',
    skin_color: 'blue',
    eye_color: 'hazel',
    birth_year: '48BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/37/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/15/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T09:48:01.172000Z',
    edited: '2014-12-20T21:17:50.409000Z',
    url: 'STRING_TO_REPLACE/api/people/46/',
    imageURL: 'STRING_TO_REPLACE/images/people/Ayla Secura.png',
  },
  {
    name: 'Ratts Tyerel',
    height: '79',
    mass: '15',
    hair_color: 'none',
    skin_color: 'grey, blue',
    eye_color: 'unknown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/38/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/16/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T09:53:15.086000Z',
    edited: '2014-12-20T21:17:50.410000Z',
    url: 'STRING_TO_REPLACE/api/people/47/',
    imageURL: 'STRING_TO_REPLACE/images/people/Ratts Tyerel.png',
  },
  {
    name: 'Dud Bolt',
    height: '94',
    mass: '45',
    hair_color: 'none',
    skin_color: 'blue, grey',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/39/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/17/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T09:57:31.858000Z',
    edited: '2014-12-20T21:17:50.414000Z',
    url: 'STRING_TO_REPLACE/api/people/48/',
    imageURL: 'STRING_TO_REPLACE/images/people/Dud Bolt.png',
  },
  {
    name: 'Gasgano',
    height: '122',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'white, blue',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/40/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/18/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:02:12.223000Z',
    edited: '2014-12-20T21:17:50.416000Z',
    url: 'STRING_TO_REPLACE/api/people/49/',
    imageURL: 'STRING_TO_REPLACE/images/people/Gasgano.png',
  },
  {
    name: 'Ben Quadinaros',
    height: '163',
    mass: '65',
    hair_color: 'none',
    skin_color: 'grey, green, yellow',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/41/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/19/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:08:33.777000Z',
    edited: '2014-12-20T21:17:50.417000Z',
    url: 'STRING_TO_REPLACE/api/people/50/',
    imageURL: 'STRING_TO_REPLACE/images/people/Ben Quadinaros.png',
  },
  {
    name: 'Mace Windu',
    height: '188',
    mass: '84',
    hair_color: 'none',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '72BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/42/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:12:30.846000Z',
    edited: '2014-12-20T21:17:50.420000Z',
    url: 'STRING_TO_REPLACE/api/people/51/',
    imageURL: 'STRING_TO_REPLACE/images/people/Mace Windu.png',
  },
  {
    name: 'Ki-Adi-Mundi',
    height: '198',
    mass: '82',
    hair_color: 'white',
    skin_color: 'pale',
    eye_color: 'yellow',
    birth_year: '92BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/43/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/20/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:15:32.293000Z',
    edited: '2014-12-20T21:17:50.422000Z',
    url: 'STRING_TO_REPLACE/api/people/52/',
    imageURL: 'STRING_TO_REPLACE/images/people/Ki-Adi-Mundi.png',
  },
  {
    name: 'Kit Fisto',
    height: '196',
    mass: '87',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/44/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/21/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:18:57.202000Z',
    edited: '2014-12-20T21:17:50.424000Z',
    url: 'STRING_TO_REPLACE/api/people/53/',
    imageURL: 'STRING_TO_REPLACE/images/people/Kit Fisto.png',
  },
  {
    name: 'Eeth Koth',
    height: '171',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'brown',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/45/',
    films: ['STRING_TO_REPLACE/api/films/4/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/22/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:26:47.902000Z',
    edited: '2014-12-20T21:17:50.427000Z',
    url: 'STRING_TO_REPLACE/api/people/54/',
    imageURL: 'STRING_TO_REPLACE/images/people/Eeth Koth.png',
  },
  {
    name: 'Adi Gallia',
    height: '184',
    mass: '50',
    hair_color: 'none',
    skin_color: 'dark',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/9/',
    films: ['STRING_TO_REPLACE/api/films/4/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/23/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:29:11.661000Z',
    edited: '2014-12-20T21:17:50.432000Z',
    url: 'STRING_TO_REPLACE/api/people/55/',
    imageURL: 'STRING_TO_REPLACE/images/people/Adi Gallia.png',
  },
  {
    name: 'Saesee Tiin',
    height: '188',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/47/',
    films: ['STRING_TO_REPLACE/api/films/4/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/24/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:32:11.669000Z',
    edited: '2014-12-20T21:17:50.434000Z',
    url: 'STRING_TO_REPLACE/api/people/56/',
    imageURL: 'STRING_TO_REPLACE/images/people/Saesee Tiin.png',
  },
  {
    name: 'Yarael Poof',
    height: '264',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/48/',
    films: ['STRING_TO_REPLACE/api/films/4/'],
    species: ['STRING_TO_REPLACE/api/species/25/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:34:48.725000Z',
    edited: '2014-12-20T21:17:50.437000Z',
    url: 'STRING_TO_REPLACE/api/people/57/',
    imageURL: 'STRING_TO_REPLACE/images/people/Yarael Poof.png',
  },
  {
    name: 'Plo Koon',
    height: '188',
    mass: '80',
    hair_color: 'none',
    skin_color: 'orange',
    eye_color: 'black',
    birth_year: '22BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/49/',
    films: [
      'STRING_TO_REPLACE/api/films/4/',
      'STRING_TO_REPLACE/api/films/5/',
      'STRING_TO_REPLACE/api/films/6/',
    ],
    species: ['STRING_TO_REPLACE/api/species/26/'],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/48/'],
    created: '2014-12-20T10:49:19.859000Z',
    edited: '2014-12-20T21:17:50.439000Z',
    url: 'STRING_TO_REPLACE/api/people/58/',
    imageURL: 'STRING_TO_REPLACE/images/people/Plo Koon.png',
  },
  {
    name: 'Mas Amedda',
    height: '196',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'blue',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/50/',
    films: ['STRING_TO_REPLACE/api/films/4/', 'STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/27/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T10:53:26.457000Z',
    edited: '2014-12-20T21:17:50.442000Z',
    url: 'STRING_TO_REPLACE/api/people/59/',
    imageURL: 'STRING_TO_REPLACE/images/people/Mas Amedda.png',
  },
  {
    name: 'Gregar Typho',
    height: '185',
    mass: '85',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: [],
    vehicles: [],
    starships: ['STRING_TO_REPLACE/api/starships/39/'],
    created: '2014-12-20T11:10:10.381000Z',
    edited: '2014-12-20T21:17:50.445000Z',
    url: 'STRING_TO_REPLACE/api/people/60/',
    imageURL: 'STRING_TO_REPLACE/images/people/Gregar Typho.png',
  },
  {
    name: 'Cordé',
    height: '157',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T11:11:39.630000Z',
    edited: '2014-12-20T21:17:50.449000Z',
    url: 'STRING_TO_REPLACE/api/people/61/',
    imageURL: 'STRING_TO_REPLACE/images/people/Cordé.png',
  },
  {
    name: 'Cliegg Lars',
    height: '183',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '82BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/1/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T15:59:03.958000Z',
    edited: '2014-12-20T21:17:50.451000Z',
    url: 'STRING_TO_REPLACE/api/people/62/',
    imageURL: 'STRING_TO_REPLACE/images/people/Cliegg Lars.png',
  },
  {
    name: 'Poggle the Lesser',
    height: '183',
    mass: '80',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/11/',
    films: ['STRING_TO_REPLACE/api/films/5/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/28/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T16:40:43.977000Z',
    edited: '2014-12-20T21:17:50.453000Z',
    url: 'STRING_TO_REPLACE/api/people/63/',
    imageURL: 'STRING_TO_REPLACE/images/people/Poggle the Lesser.png',
  },
  {
    name: 'Luminara Unduli',
    height: '170',
    mass: '56.2',
    hair_color: 'black',
    skin_color: 'yellow',
    eye_color: 'blue',
    birth_year: '58BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/51/',
    films: ['STRING_TO_REPLACE/api/films/5/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/29/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T16:45:53.668000Z',
    edited: '2014-12-20T21:17:50.455000Z',
    url: 'STRING_TO_REPLACE/api/people/64/',
    imageURL: 'STRING_TO_REPLACE/images/people/Luminara Unduli.png',
  },
  {
    name: 'Barriss Offee',
    height: '166',
    mass: '50',
    hair_color: 'black',
    skin_color: 'yellow',
    eye_color: 'blue',
    birth_year: '40BBY',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/51/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/29/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T16:46:40.440000Z',
    edited: '2014-12-20T21:17:50.457000Z',
    url: 'STRING_TO_REPLACE/api/people/65/',
    imageURL: 'STRING_TO_REPLACE/images/people/Barriss Offee.png',
  },
  {
    name: 'Dormé',
    height: '165',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/8/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/1/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T16:49:14.640000Z',
    edited: '2014-12-20T21:17:50.460000Z',
    url: 'STRING_TO_REPLACE/api/people/66/',
    imageURL: 'STRING_TO_REPLACE/images/people/Dormé.png',
  },
  {
    name: 'Dooku',
    height: '193',
    mass: '80',
    hair_color: 'white',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '102BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/52/',
    films: ['STRING_TO_REPLACE/api/films/5/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/1/'],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/55/'],
    starships: [],
    created: '2014-12-20T16:52:14.726000Z',
    edited: '2014-12-20T21:17:50.462000Z',
    url: 'STRING_TO_REPLACE/api/people/67/',
    imageURL: 'STRING_TO_REPLACE/images/people/Dooku.png',
  },
  {
    name: 'Bail Prestor Organa',
    height: '191',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'tan',
    eye_color: 'brown',
    birth_year: '67BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/2/',
    films: ['STRING_TO_REPLACE/api/films/5/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/1/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T16:53:08.575000Z',
    edited: '2014-12-20T21:17:50.463000Z',
    url: 'STRING_TO_REPLACE/api/people/68/',
    imageURL: 'STRING_TO_REPLACE/images/people/Bail Prestor Organa.png',
  },
  {
    name: 'Jango Fett',
    height: '183',
    mass: '79',
    hair_color: 'black',
    skin_color: 'tan',
    eye_color: 'brown',
    birth_year: '66BBY',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/53/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T16:54:41.620000Z',
    edited: '2014-12-20T21:17:50.465000Z',
    url: 'STRING_TO_REPLACE/api/people/69/',
    imageURL: 'STRING_TO_REPLACE/images/people/Jango Fett.png',
  },
  {
    name: 'Zam Wesell',
    height: '168',
    mass: '55',
    hair_color: 'blonde',
    skin_color: 'fair, green, yellow',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/54/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/30/'],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/45/'],
    starships: [],
    created: '2014-12-20T16:57:44.471000Z',
    edited: '2014-12-20T21:17:50.468000Z',
    url: 'STRING_TO_REPLACE/api/people/70/',
    imageURL: 'STRING_TO_REPLACE/images/people/Zam Wesell.png',
  },
  {
    name: 'Dexter Jettster',
    height: '198',
    mass: '102',
    hair_color: 'none',
    skin_color: 'brown',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/55/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/31/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T17:28:27.248000Z',
    edited: '2014-12-20T21:17:50.470000Z',
    url: 'STRING_TO_REPLACE/api/people/71/',
    imageURL: 'STRING_TO_REPLACE/images/people/Dexter Jettster.png',
  },
  {
    name: 'Lama Su',
    height: '229',
    mass: '88',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/10/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/32/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T17:30:50.416000Z',
    edited: '2014-12-20T21:17:50.473000Z',
    url: 'STRING_TO_REPLACE/api/people/72/',
    imageURL: 'STRING_TO_REPLACE/images/people/Lama Su.png',
  },
  {
    name: 'Taun We',
    height: '213',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/10/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/32/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T17:31:21.195000Z',
    edited: '2014-12-20T21:17:50.474000Z',
    url: 'STRING_TO_REPLACE/api/people/73/',
    imageURL: 'STRING_TO_REPLACE/images/people/Taun We.png',
  },
  {
    name: 'Jocasta Nu',
    height: '167',
    mass: 'unknown',
    hair_color: 'white',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/9/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/1/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T17:32:51.996000Z',
    edited: '2014-12-20T21:17:50.476000Z',
    url: 'STRING_TO_REPLACE/api/people/74/',
    imageURL: 'STRING_TO_REPLACE/images/people/Jocasta Nu.png',
  },
  {
    name: 'R4-P17',
    height: '96',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'silver, red',
    eye_color: 'red, blue',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/28/',
    films: ['STRING_TO_REPLACE/api/films/5/', 'STRING_TO_REPLACE/api/films/6/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T17:43:36.409000Z',
    edited: '2014-12-20T21:17:50.478000Z',
    url: 'STRING_TO_REPLACE/api/people/75/',
    imageURL: 'STRING_TO_REPLACE/images/people/R4-P17.png',
  },
  {
    name: 'Wat Tambor',
    height: '193',
    mass: '48',
    hair_color: 'none',
    skin_color: 'green, grey',
    eye_color: 'unknown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/56/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/33/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T17:53:52.607000Z',
    edited: '2014-12-20T21:17:50.481000Z',
    url: 'STRING_TO_REPLACE/api/people/76/',
    imageURL: 'STRING_TO_REPLACE/images/people/Wat Tambor.png',
  },
  {
    name: 'San Hill',
    height: '191',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'gold',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/57/',
    films: ['STRING_TO_REPLACE/api/films/5/'],
    species: ['STRING_TO_REPLACE/api/species/34/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T17:58:17.049000Z',
    edited: '2014-12-20T21:17:50.484000Z',
    url: 'STRING_TO_REPLACE/api/people/77/',
    imageURL: 'STRING_TO_REPLACE/images/people/San Hill.png',
  },
  {
    name: 'Shaak Ti',
    height: '178',
    mass: '57',
    hair_color: 'none',
    skin_color: 'red, blue, white',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/58/',
    films: ['STRING_TO_REPLACE/api/films/5/', 'STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/35/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T18:44:01.103000Z',
    edited: '2014-12-20T21:17:50.486000Z',
    url: 'STRING_TO_REPLACE/api/people/78/',
    imageURL: 'STRING_TO_REPLACE/images/people/Shaak Ti.png',
  },
  {
    name: 'Grievous',
    height: '216',
    mass: '159',
    hair_color: 'none',
    skin_color: 'brown, white',
    eye_color: 'green, yellow',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/59/',
    films: ['STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/36/'],
    vehicles: ['STRING_TO_REPLACE/api/vehicles/60/'],
    starships: ['STRING_TO_REPLACE/api/starships/74/'],
    created: '2014-12-20T19:43:53.348000Z',
    edited: '2014-12-20T21:17:50.488000Z',
    url: 'STRING_TO_REPLACE/api/people/79/',
    imageURL: 'STRING_TO_REPLACE/images/people/Grievous.png',
  },
  {
    name: 'Tarfful',
    height: '234',
    mass: '136',
    hair_color: 'brown',
    skin_color: 'brown',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/14/',
    films: ['STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/3/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T19:46:34.209000Z',
    edited: '2014-12-20T21:17:50.491000Z',
    url: 'STRING_TO_REPLACE/api/people/80/',
    imageURL: 'STRING_TO_REPLACE/images/people/Tarfful.png',
  },
  {
    name: 'Raymus Antilles',
    height: '188',
    mass: '79',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/2/',
    films: ['STRING_TO_REPLACE/api/films/1/', 'STRING_TO_REPLACE/api/films/6/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T19:49:35.583000Z',
    edited: '2014-12-20T21:17:50.493000Z',
    url: 'STRING_TO_REPLACE/api/people/81/',
    imageURL: 'STRING_TO_REPLACE/images/people/Raymus Antilles.png',
  },
  {
    name: 'Sly Moore',
    height: '178',
    mass: '48',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'white',
    birth_year: 'unknown',
    gender: 'female',
    homeworld: 'STRING_TO_REPLACE/api/planets/60/',
    films: ['STRING_TO_REPLACE/api/films/5/', 'STRING_TO_REPLACE/api/films/6/'],
    species: [],
    vehicles: [],
    starships: [],
    created: '2014-12-20T20:18:37.619000Z',
    edited: '2014-12-20T21:17:50.496000Z',
    url: 'STRING_TO_REPLACE/api/people/82/',
    imageURL: 'STRING_TO_REPLACE/images/people/Sly Moore.png',
  },
  {
    name: 'Tion Medon',
    height: '206',
    mass: '80',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'STRING_TO_REPLACE/api/planets/12/',
    films: ['STRING_TO_REPLACE/api/films/6/'],
    species: ['STRING_TO_REPLACE/api/species/37/'],
    vehicles: [],
    starships: [],
    created: '2014-12-20T20:35:04.260000Z',
    edited: '2014-12-20T21:17:50.498000Z',
    url: 'STRING_TO_REPLACE/api/people/83/',
    imageURL: 'STRING_TO_REPLACE/images/people/Tion Medon.png',
  },
];
